# Generated by Django 5.2.5 on 2025-08-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gist;"),
        migrations.RunSQL("""
            ALTER TABLE bookings_booking
            ADD COLUMN time_range tstzrange GENERATED ALWAYS AS (tstzrange(requested_start_utc, requested_end_utc, '[]')) STORED;
        """),
        migrations.RunSQL("""
            ALTER TABLE bookings_booking
            ADD CONSTRAINT no_overlapping_confirmed_bookings
            EXCLUDE USING GIST (
                mentor_id WITH =,
                time_range WITH &&
            )
            WHERE (status = 'confirmed');
        """),
    ]
