# Generated by Django 5.2.5 on 2025-08-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20250809_1540'),
        ('skills', '0002_mentortag_skillcategory_alter_mentorskill_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('schedule_conflict', 'Schedule Conflict'), ('emergency', 'Emergency'), ('illness', 'Illness'), ('technical_issues', 'Technical Issues'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_end_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_start_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='learner_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='learner_notes',
            field=models.TextField(blank=True, help_text='Notes from learner about what they want to learn'),
        ),
        migrations.AddField(
            model_name='booking',
            name='learner_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Video call link'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_notes',
            field=models.TextField(blank=True, help_text='Notes from mentor about the session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills to focus on during session', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='booking',
            name='subject',
            field=models.CharField(default='General Session', help_text='What will be covered in this session', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='learner',
            field=models.ForeignKey(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='learner_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled_by_learner', 'Cancelled by Learner'), ('cancelled_by_mentor', 'Cancelled by Mentor'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_show_learner', 'No Show - Learner'), ('no_show_mentor', 'No Show - Mentor')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mentor', 'status'], name='bookings_bo_mentor__8d31b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['learner', 'status'], name='bookings_bo_learner_327f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'requested_start_utc'], name='bookings_bo_status_473299_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['requested_start_utc', 'requested_end_utc'], name='bookings_bo_request_b8e729_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('requested_start_utc__lt', models.F('requested_end_utc'))), name='requested_start_before_end'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
