# Generated by Django 5.2.5 on 2025-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingstatushistory_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.CharField(default='Mentoring Session', help_text='What will be covered in this session', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='to_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
