# Generated by Django 5.2.5 on 2025-08-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_subject_and_more'),
        ('mentoring_sessions', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_booking_requests', models.BooleanField(default=True)),
                ('email_booking_confirmations', models.BooleanField(default=True)),
                ('email_session_reminders', models.BooleanField(default=True)),
                ('email_feedback_received', models.BooleanField(default=True)),
                ('email_general_updates', models.BooleanField(default=True)),
                ('push_booking_requests', models.BooleanField(default=True)),
                ('push_booking_confirmations', models.BooleanField(default=True)),
                ('push_session_reminders', models.BooleanField(default=True)),
                ('push_feedback_received', models.BooleanField(default=False)),
                ('push_general_updates', models.BooleanField(default=False)),
                ('session_reminder_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before session to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Text for action button', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL for action button'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When notification expires', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mentoring_sessions.session'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='Notification', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data related to notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('session_starting', 'Session Starting Soon'), ('session_reminder', 'Session Reminder'), ('feedback_received', 'Feedback Received'), ('mentor_approved', 'Mentor Application Approved'), ('mentor_rejected', 'Mentor Application Rejected'), ('availability_conflict', 'Availability Conflict'), ('payment_received', 'Payment Received'), ('general', 'General'), ('system', 'System Notification')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_60753b_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
