# Generated by Django 5.2.5 on 2025-08-09 12:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mentorskill',
            options={'ordering': ['-is_primary', '-proficiency', 'skill__name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-popularity', 'name']},
        ),
        migrations.AddField(
            model_name='mentorskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorskill',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorskill',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 9, 12, 7, 16, 430413, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorskill',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorskill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=3, help_text='1=Beginner, 5=Expert'),
        ),
        migrations.AlterField(
            model_name='mentorskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skills', to='skills.skill'),
        ),
        migrations.AddIndex(
            model_name='mentorskill',
            index=models.Index(fields=['mentor', 'is_primary'], name='skills_ment_mentor__8a19b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorskill',
            index=models.Index(fields=['skill', 'proficiency'], name='skills_ment_skill_i_7bf2d0_idx'),
        ),
        migrations.AddField(
            model_name='mentortag',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillcategory'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active', 'popularity'], name='skills_skil_is_acti_59531c_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'popularity'], name='skills_skil_categor_bb3031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentortag',
            unique_together={('mentor', 'tag')},
        ),
    ]
