# Generated by Django 5.2.5 on 2025-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_mentortag_skillcategory_alter_mentorskill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortag',
            name='tag',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
