# Generated by Django 5.2.5 on 2025-08-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('is_full_day', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('recurring_rule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['mentor', 'start_utc'], name='availabilit_mentor__df4cdf_idx')],
            },
        ),
    ]
