# Generated by Django 5.2.5 on 2025-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_mentoravailabilitysettings_weeklyavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
