# Generated by Django 5.2.5 on 2025-08-09 14:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0003_alter_mentortag_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_mentors', models.PositiveIntegerField(default=0)),
                ('active_mentors', models.PositiveIntegerField(default=0)),
                ('new_mentors', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('cancelled_sessions', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mentor_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_session_rating', models.FloatField(default=0.0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LearnerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('cancelled_sessions', models.PositiveIntegerField(default=0)),
                ('no_show_sessions', models.PositiveIntegerField(default=0)),
                ('skills_learned', models.PositiveIntegerField(default=0)),
                ('goals_achieved', models.PositiveIntegerField(default=0)),
                ('total_learning_hours', models.FloatField(default=0.0)),
                ('this_month_hours', models.FloatField(default=0.0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('this_month_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_session_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('mentors_worked_with', models.PositiveIntegerField(default=0)),
                ('favorite_mentors', models.PositiveIntegerField(default=0)),
                ('reviews_given', models.PositiveIntegerField(default=0)),
                ('preferred_session_duration', models.PositiveIntegerField(default=60)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.OneToOneField(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='learner_analytics', to=settings.AUTH_USER_MODEL)),
                ('most_booked_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('cancelled_sessions', models.PositiveIntegerField(default=0)),
                ('no_show_sessions', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('five_star_reviews', models.PositiveIntegerField(default=0)),
                ('four_star_reviews', models.PositiveIntegerField(default=0)),
                ('three_star_reviews', models.PositiveIntegerField(default=0)),
                ('two_star_reviews', models.PositiveIntegerField(default=0)),
                ('one_star_reviews', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('this_month_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_month_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_response_time_hours', models.FloatField(default=0.0)),
                ('response_rate_percentage', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('profile_views_this_month', models.PositiveIntegerField(default=0)),
                ('profile_views_total', models.PositiveIntegerField(default=0)),
                ('repeat_learners', models.PositiveIntegerField(default=0)),
                ('total_teaching_hours', models.FloatField(default=0.0)),
                ('this_month_hours', models.FloatField(default=0.0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.OneToOneField(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('unique_learners', models.PositiveIntegerField(default=0)),
                ('total_mentors', models.PositiveIntegerField(default=0)),
                ('active_mentors', models.PositiveIntegerField(default=0)),
                ('average_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('min_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('max_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('popularity_rank', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='skills.skill')),
            ],
            options={
                'ordering': ['popularity_rank', '-total_sessions'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('search', 'Search'), ('profile_view', 'Profile View'), ('booking_created', 'Booking Created'), ('booking_completed', 'Booking Completed'), ('message_sent', 'Message Sent'), ('rating_given', 'Rating Given'), ('skill_learned', 'Skill Learned'), ('goal_achieved', 'Goal Achieved')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type'], name='analytics_a_user_id_7df679_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['created_at'], name='analytics_a_created_546677_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('searches_performed', models.PositiveIntegerField(default=0)),
                ('profiles_viewed', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('bookings_made', models.PositiveIntegerField(default=0)),
                ('reviews_given', models.PositiveIntegerField(default=0)),
                ('sessions_attended', models.PositiveIntegerField(default=0)),
                ('learning_hours', models.FloatField(default=0.0)),
                ('sessions_taught', models.PositiveIntegerField(default=0)),
                ('teaching_hours', models.FloatField(default=0.0)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_u_user_id_2064f7_idx'), models.Index(fields=['date'], name='analytics_u_date_aa1b1e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
