# Generated by Django 5.2.5 on 2025-08-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('recommendation', 'Recommendation')], max_length=32)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='ai_airespon_type_2a380d_idx')],
            },
        ),
    ]
