# Generated by Django 5.2.5 on 2025-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_search_vector_user_users_is_avai_e026af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='provider',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='social_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.CharField(default='learning', max_length=100),
        ),
    ]
